---
- name: intall Web server
  hosts: rhel8
  tasks:
  - name: Install http service
    yum:
      name: httpd
      state: latest
  - name: service httpd
    service:
      name: httpd
      state: started
  - name: Firewalld enable
    firewalld:
      service: http
      permanent : true
      state: enabled
      immediate: yes